language: java
env:
  matrix:
    - PLATFORM=railo41
  global:
    - secure: "eAZHEqLif27bfXxkm7g9xuf2jeY4H2vIyY8RHRa51O83ujOraqbtkv6AcwCEJLQv9OkC5wFTALOkRAIk06BoDAKM1gS5i0zFkMjYMDzVPChDDM4a85ZQxsgTV0zsqerP/eAsYZXqCENMpbodmGBqMK0lrdaDj/KjSHtHQK5gxJc="
    - secure: "NsRz2tIuwbGbt76ZA+Cmrrl/27p7LvT+VF0dfYIlTIhThOK+zYXrSyGMtni/ygc83BNRromnaU5kUFn+TG46MqADHwflspBiPRWYX3bnfa1Y0Uzs1Og5yihJZEmcgde0nkFhfjpuoY33F/QwMDv8nYZSKMCp32VppJoINr2jMFs="
install: ant -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM install-ci-deps
script: ant -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM test-ci
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash